version: '3.7'

services:
  gateway:
    image: daa/gateway:test
    build:
      context: .
      dockerfile: ./SVC.Gateway/Dockerfile
      args:
        APPNAME: Gateway
    ports:
      - "5000:80"
    depends_on:
      - users
    environment:
      ASPNETCORE_ENVIRONMENT: "Local"
  users:
    image: daa/users:test
    build:
      context: .
      dockerfile: ./SVC.Users/Dockerfile
      args:
        APPNAME: Users
    ports:
      - "5001:80"
    depends_on:
      - database
    environment:
      ConnectionStrings__Users: "Server=database;Database=Daa_Users;User=sa;Password=Your_password123;"
      ASPNETCORE_ENVIRONMENT: "Local"
  database:
    image: "mcr.microsoft.com/mssql/server:2017-CU14-ubuntu"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
